CREATE DATABASE LIBRARYMANGAE
-- DROP DATABASE LIBRARYMANGAE
Use master
USE LIBRARYMANGAE

--------------------------------------- TẠO BẢNG -----------------------------------------
-- SINH VIÊN
CREATE TABLE Admin(
[UserAdmin] [varchar](30) primary key,
[PassAdmin] [varchar](30) NOT NULL,
[Hoten] [nvarchar](50) NOT NULL
)

CREATE TABLE classs(
classid [varchar](30) primary key,
)
CREATE TABLE studenss(
studenssid [varchar](30) primary key,
classid [varchar](30)
)

CREATE TABLE STUDENT (
	STUDENT_ID CHAR(10) NOT NULL,
	STUDENT_NAME NVARCHAR(100),
	PHONE INT,
	"ADDRESS" NVARCHAR(150),
	EMAIL NVARCHAR(50),
	CLASS_ID CHAR(10),
	COURSE_ID CHAR(10),
	SUBJECT_ID CHAR(10),
	DATE_ADD DATE,
	DATE_REPAIR DATE,
 CONSTRAINT [PK_STUDENT] PRIMARY KEY CLUSTERED (STUDENT_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

--------- LỚP, KHÓA, MÔN HỌC
CREATE TABLE COURSE (
	COURSE_ID CHAR(10) NOT NULL,
	COURSE_NAME NVARCHAR(15),
 CONSTRAINT [PK_COURSE] PRIMARY KEY CLUSTERED (COURSE_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE CLASS (
	CLASS_ID CHAR(10) NOT NULL,
	CLASS_NAME NVARCHAR(15),
	CLASS_PRESIDENT NVARCHAR(100),
 CONSTRAINT [PK_CLASS] PRIMARY KEY CLUSTERED (CLASS_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE "SUBJECT" (
	SUBJECT_ID CHAR(10) NOT NULL,
	SUBJECT_NAME NVARCHAR(15),
 CONSTRAINT [PK_SUBJECT] PRIMARY KEY CLUSTERED (SUBJECT_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
---------

-- SÁCH
CREATE TABLE BOOKS (
	BOOK_ID CHAR(10) NOT NULL,
	BOOK_NAME NVARCHAR(50),
	QUANTITY INT,
	UNIT_PRICE INT,
	AUTHOR_ID CHAR(10),
	TYPE_BOOK_ID CHAR(10),
	PUBLISHER_ID CHAR(10),
	PUBLISHING_YEAR DATE,
	DATE_RECEIPT DATE,
 CONSTRAINT [PK_BOOKS] PRIMARY KEY CLUSTERED (BOOK_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

--------- TÁC GIẢ, LOẠI SÁCH, NSX
CREATE TABLE AUTHOR(
	AUTHOR_ID CHAR(10)NOT NULL,
	AUTHOR_NAME NVARCHAR(50),
 CONSTRAINT [PK_AUTHOR] PRIMARY KEY CLUSTERED (AUTHOR_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE TYPE_BOOK(
	TYPE_BOOK_ID CHAR(10)NOT NULL,
	TYPE_BOOK_NAME NVARCHAR(50),
 CONSTRAINT [PK_TYPE_BOOK] PRIMARY KEY CLUSTERED (TYPE_BOOK_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE PUBLISHER(
	PUBLISHER_ID CHAR(10),
	PUBLISHER_NAME NVARCHAR(50),
 CONSTRAINT [PK_PUBLISHER] PRIMARY KEY CLUSTERED (PUBLISHER_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
---------

--------- HÓA ĐƠN, PHIẾU NHẬP
CREATE TABLE BILLS (
	BILL_ID CHAR(10) NOT NULL,
	STUDENT_ID CHAR(10),
	BILL_DATE DATE,
	TOTAL INT,
 CONSTRAINT [PK_BILLS] PRIMARY KEY CLUSTERED (BILL_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE BILL_DETAIL (
	BILL_DETAIL_ID CHAR(10) NOT NULL,
	BILL_ID CHAR(10),
	BOOK_ID CHAR(10),
	AMOUNT INT,
	UNIT_PRICE INT,
 CONSTRAINT [PK_BILL_DETAIL] PRIMARY KEY CLUSTERED (BILL_DETAIL_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
 /**
CREATE TABLE RECEIPT (
	RECEIPT_ID CHAR(10) NOT NULL,
	BOOK_ID CHAR(10),
	DATE_RECEIPT DATE,
 CONSTRAINT [PK_RECEIPT] PRIMARY KEY CLUSTERED (RECEIPT_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]

CREATE TABLE RECEIPT_DETAIL (
	RECEIPT_DETAIL_ID CHAR(10) NOT NULL,
	RECEIPT_ID CHAR(10),
	QUANTITY INT,
	UNIT_PRICE INT,
 CONSTRAINT [PK_RECEIPT_DETAIL] PRIMARY KEY CLUSTERED (RECEIPT_DETAIL_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
 **/
---------

--------- NHẬN SÁCH
CREATE TABLE RECEIVING_BOOKS (
	RECEIVING_BOOK_ID CHAR(10) NOT NULL,
	RECEIVED_DATE DATE,
 CONSTRAINT [PK_RECEIVING_BOOKS] PRIMARY KEY CLUSTERED (RECEIVING_BOOK_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
 /**
CREATE TABLE RECEIVING_BOOK_DETAIL (
	RECEIVING_BOOK_DETAIL_ID CHAR(10) NOT NULL,
	RECEIVING_BOOK_ID CHAR(10),
 CONSTRAINT [PK_RECEIVING_BOOK_DETAIL] PRIMARY KEY CLUSTERED (RECEIVING_BOOK_DETAIL_ID ASC ) WITH
 (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
 ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]
 **/
---------
------------------------------------------------------------------------------------------
-- DROP TABLE "SUBJECT"

--------- THÊM CỘT ---------
ALTER TABLE RECEIVING_BOOKS
  ADD 
	STUDENT_ID CHAR(10),
	BOOK_ID CHAR(10)
	
ALTER TABLE AUTHOR
  ADD 
	PUBLISHER_ID CHAR(10)
ALTER TABLE TYPE_BOOK
  ADD 
	AUTHOR_ID CHAR(10)

ALTER TABLE COURSE
  ADD 
	CLASS_ID CHAR(10)
ALTER TABLE CLASS
  ADD 
	SUBJECT_ID CHAR(10)
ALTER TABLE "SUBJECT"
  ADD 
	"TIME" INT

	--- ĐỔI KIỂU DỮ LIỆU ---
ALTER TABLE BOOKS
	ALTER  COLUMN BOOK_NAME NVARCHAR(150)
	
ALTER TABLE AUTHOR
	ALTER  COLUMN AUTHOR_NAME NVARCHAR(150)
	---------------
	sp_rename 'BILL_DETAIL, AMOUNT', 'QUANTITY','COLUMN';
----------------------------

--------------------------------------- TẠO KHÓA -----------------------------------------
 ALTER TABLE BILL_DETAIL WITH CHECK ADD CONSTRAINT [FK_BILL_DETAIL_BILLS] FOREIGN
KEY(BILL_ID) REFERENCES BILLS (BILL_ID)
ALTER TABLE BILL_DETAIL CHECK CONSTRAINT [FK_BILL_DETAIL_BILLS]

ALTER TABLE BILLS WITH CHECK ADD CONSTRAINT [FK_BILLS_STUDENT] FOREIGN
KEY(STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
ALTER TABLE BILLS CHECK CONSTRAINT [FK_BILLS_STUDENT]

ALTER TABLE TYPE_BOOK WITH CHECK ADD CONSTRAINT [FK_TYPE_BOOK_AUTHOR] FOREIGN
KEY(TYPE_BOOK_ID) REFERENCES AUTHOR (TYPE_BOOK_ID)
ALTER TABLE TYPE_BOOK CHECK CONSTRAINT [FK_TYPE_BOOK_AUTHOR]

ALTER TABLE AUTHOR WITH CHECK ADD CONSTRAINT [FK_AUTHOR_PUBLISHER] FOREIGN
KEY(AUTHOR_ID) REFERENCES PUBLISHER (AUTHOR_ID)
ALTER TABLE AUTHOR CHECK CONSTRAINT [FK_AUTHOR_PUBLISHER]

------------------------------------------------------------------------------------------

------------------------------------- THÊM DỮ LIỆU ---------------------------------------
--------- NHÓM SINH VIÊN
INSERT Into Admin
VALUES ('admin', '123456', 'Chủ rạp xiếc')
INSERT Into Admin
VALUES ('user', '789', 'Chúa hề')

SET IDENTITY_INSERT COURSE ON
INSERT COURSE (COURSE_ID, COURSE_NAME) VALUES ('K10', N'Khóa 10')
INSERT COURSE (COURSE_ID, COURSE_NAME) VALUES ('K11', N'Khóa 11')
INSERT COURSE (COURSE_ID, COURSE_NAME) VALUES ('K12', N'Khóa 12')
SET IDENTITY_INSERT COURSE OFF

SET IDENTITY_INSERT CLASS ON
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('LTMK10', N'Lập trình mạng', N'Nguyễn Thị A')
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('LTMK11', N'Lập trình mạng', N'Nguyễn Thị B')
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('LTMK12', N'Lập trình mạng', N'Nguyễn Thị C')
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('QTMK10', N'Quảng trị mạng', N'Nguyễn Văn A')
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('QTMK11', N'Quảng trị mạng', N'Nguyễn Văn B')
INSERT CLASS (CLASS_ID, CLASS_NAME, CLASS_PRESIDENT) VALUES ('QTMK12', N'Quảng trị mạng', N'Nguyễn Văn C')
SET IDENTITY_INSERT CLASS OFF

SET IDENTITY_INSERT "SUBJECT" ON
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SC01', N'HTML')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SC05', N'Java cơ bản')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SC02', N'CSS')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SC03', N'PHP')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SH05', N'Pyton')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SIT01', N'Chính trị')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SH06', N'Mũ đen')
INSERT "SUBJECT" (SUBJECT_ID, SUBJECT_NAME) VALUES ('SH07', N'Mũ trắng')
SET IDENTITY_INSERT "SUBJECT" OFF

SET IDENTITY_INSERT STUDENT ON
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD185461', N'Lâm Covid-19', N'0768577777', N'', N'abc1@123.com', N'QTM', N'K10', 'SH06', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD455884', N'Trần Covid-20', N'0777797777', N'', N'abc2@123.com', N'QTM', N'K11', 'SH06', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD185858', N'Lâm Covid-21', N'0771777777', N'', N'abc3@123.com', N'QTM', N'K12', 'SH06', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD141414', N'Nguyễn Chui Ra', N'0664677777', N'', N'abc4@123.com', N'LTM2', N'K10', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD152525', N'Nguyễn Đi Vào', N'0777545777', N'', N'abc5@123.com', N'LTV2', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD188868', N'Trần Văn Xỉu', N'0777771517', N'', N'abc6@123.com', N'LTM2', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD185272', N'Nguyễn Thị Cảm', N'0777894177', N'', N'abc7@123.com', N'LTM4', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD183859', N'Trịnh Cúm', N'0777894177', N'', N'abc8@123.com', N'LTM3', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD175377', N'Vương Thị Ăn', N'0777894177', N'', N'abc9@123.com', N'LTM4', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD616528', N'Vương Trương Hại', N'0777894177', N'', N'abc10@123.com', N'LTM2', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD516522', N'Lâm Nguyễn Rơi', N'0777845177', N'', N'abc11@123.com', N'LTM', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD849125', N'Trương Lệ', N'0777893477', N'', N'abc12@123.com', N'LTM3', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD195325', N'Lê Trương Cách', N'0775594177', N'', N'abc13@123.com', N'QTM', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD148589', N'Lê Ly', N'0779874177', N'', N'abc14@123.com', N'QTM4', N'K11', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD148599', N'Nguyễn Thị Đi', N'0777624177', N'', N'abc14@123.com', N'LTM2', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD148999', N'Lâm Trương Khách', N'0774999177', N'', N'abc14@123.com', N'LTM4', N'K12', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD148989', N'Vương Trương Bị', N'0774398777', N'', N'abc14@123.com', N'LTM1', N'K10', '', '')
INSERT STUDENT (STUDENT_ID, STUDENT_NAME, PHONE, "ADDRESS", EMAIL, CLASS_ID, COURSE_ID, SUBJECT_ID, DATE_ADD) VALUES ('CD18589', N'Trương Trịnh Bắt', N'0771234177', N'', N'abc14@123.com', N'LTM3', N'K10', '', '')
SET IDENTITY_INSERT STUDENT OFF
---------

--------- NHÓM SÁCH
SET IDENTITY_INSERT AUTHOR ON
INSERT AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES ('AT01', N'Nguyễn Trung Kiên')
INSERT AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES ('AT02', N'Lê Trung Cường')
SET IDENTITY_INSERT AUTHOR OFF

SET IDENTITY_INSERT TYPE_BOOK ON
INSERT TYPE_BOOK (TYPE_BOOK_ID, TYPE_BOOK_NAME) VALUES ('TB01', N'Lập trình')
INSERT TYPE_BOOK (TYPE_BOOK_ID, TYPE_BOOK_NAME) VALUES ('TB02', N'Quản trị')
INSERT TYPE_BOOK (TYPE_BOOK_ID, TYPE_BOOK_NAME) VALUES ('TB03', N'Chính trị')
INSERT TYPE_BOOK (TYPE_BOOK_ID, TYPE_BOOK_NAME) VALUES ('TB04', N'Xã Hội')
INSERT TYPE_BOOK (TYPE_BOOK_ID, TYPE_BOOK_NAME) VALUES ('TB05', N'Kinh tế')
SET IDENTITY_INSERT TYPE_BOOK OFF

SET IDENTITY_INSERT PUBLISHER ON
INSERT PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME) VALUES ('PL01', N'Lao Động')
INSERT PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME) VALUES ('PL02', N'Chính trị quốc gia - sự thật')
INSERT PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME) VALUES ('PL03', N'Đại học Quốc Gia Hà Nội')
SET IDENTITY_INSERT PUBLISHER OFF
---------
------------------------------------------------------------------------------------------

SELECT * FROM CLASS
DELETE FROM PUBLISHER